[package]
name = "klaver-wintercg"
version = "0.1.0"
edition = "2024"

[features]
default = ["module"]
module = ["klaver-modules"]

[dependencies]
klaver-base = { path = "../klaver-base" }
klaver-timers = { path = "../klaver-timers" }
klaver-worker = { path = "../klaver-worker" }
klaver-fetch = { path = "../klaver-fetch" }
klaver-modules = { path = "../klaver-modules", optional = true }

rquickjs.workspace = true
rquickjs-util = { path = "../rquickjs-util" }
