[package]
name = "klaver-wintercg"
version = "0.1.0"
edition = "2021"

[dependencies]
klaver = { path = "../klaver" }
rquickjs.workspace = true
futures = { version = "0.3" }
tokio = { version = "1", features = ["sync"] }
async-stream = { version = "0.3" }
