[package]
name = "klaver-structuredclone"
version = "0.1.0"
edition = "2024"

[dependencies]
rquickjs.workspace = true
rquickjs-util = { path = "../rquickjs-util" }
ordered-float = { version = "5", features = ["serde"] }

serde = { version = "1", features = ["derive"] }
