[package]
name = "klaver"
version = "0.1.0"
edition = "2021"

[features]
default = ["pool"]
pool = ["deadpool", "tokio/rt", "tokio/sync"]
typescript = [
  "swc",
  "swc_common",
  "swc_ecma_ast",
  "swc_ecma_visit",
  "swc_ecma_parser",
  "swc_ecma_transforms",
]


[dependencies]
samling = { git = "https://github.com/fairy-render/samling" }
klaver-shared = { path = "../klaver-shared" }
rquickjs = { workspace = true, features = ["full-async", "parallel"] }
once_cell = "1"
tokio = { version = "1", features = ["macros", "time"] }
pin-project-lite = "0.2"
slotmap = { version = "1" }
extensions = { version = "0.2" }
deadpool = { version = "0.12", optional = true }
relative-path = { version = "1" }
tracing = { version = "0.1" }
parking_lot = { version = "0.12" }

# Typescript
swc = { version = "0.284.0", optional = true }
swc_common = { version = "0.37.2", optional = true }
swc_ecma_ast = { version = "0.118.1", optional = true }
swc_ecma_parser = { version = "0.149.0", features = [
  "verify",
  "typescript",
], optional = true }
swc_ecma_visit = { version = "0.104.5", optional = true }
swc_ecma_transforms = { version = "0.238.0", optional = true }
