[package]
name = "klaver-shared"
version = "0.1.0"
edition = "2021"

[features]
default = []
chrono = ["dep:chrono"]
vaerdi = ["dep:vaerdi", "chrono"]
channel = ["tokio"]

[dependencies]
rquickjs.workspace = true
rquickjs-util = { path = "../rquickjs-util" }
chrono = { version = "0.4", optional = true }
vaerdi = { git = "https://github.com/kildevaeld/vaerdi-rs", optional = true }
futures.workspace = true
tokio = { version = "1", features = ["sync"], optional = true }
