[package]
name = "klaver-test"
version = "0.1.0"
edition = "2024"

[dependencies]
klaver-core = { path = "../klaver-core" }
klaver-modules = { path = "../klaver-modules" }
rquickjs.workspace = true
futures.workspace = true

[dev-dependencies]
klaver-vm = { path = "../klaver-vm" }
tokio = { version = "1", features = ["rt", "macros"] }
