[package]
name = "rquickjs-modules"
version = "0.2.0"
edition = "2021"

[features]
default = ["swc-transform"]
oxc-transform = ["oxc"]
swc-transform = [
  "swc_node_comments",
  "swc_ecma_codegen",
  "swc_ecma_transforms",
  "swc_common",
  "swc_ecma_parser",
  "swc_ecma_ast",
  "swc_ecma_visit",
  "anyhow",
  "sourcemap",
]


[dependencies]
rquickjs = { workspace = true, features = ["loader", "futures"] }
rquickjs-util = { path = "../rquickjs-util" }
oxc_resolver = { version = "2" }
oxc = { version = "0.38", features = [
  "transformer",
  "codegen",
  "sourcemap",
  "semantic",
], optional = true }
relative-path = { version = "1" }
parking_lot = { version = "0.12" }

tracing = { version = "0.1" }
geenie = { git = "https://github.com/fairy-render/geenie.git" }

# swc = { version = "13.0", optional = true }
swc_ecma_codegen = { version = "6.0", optional = true }
swc_ecma_transforms = { version = "11.0", features = [
  "proposal",
  "compat",
  "module",
  "typescript",
  "react",
  "concurrent",
], optional = true }
swc_common = { version = "6.0", features = ["sourcemap"], optional = true }
swc_ecma_parser = { version = "8.0", optional = true }
swc_ecma_ast = { version = "6.1", optional = true }
swc_ecma_visit = { version = "6.0", optional = true }
swc_node_comments = { version = "6.0", optional = true }
sourcemap = { version = "9", optional = true }
anyhow = { version = "1", optional = true }

[dev-dependencies]
futures = { version = "0.3" }
