[package]
name = "rquickjs-modules"
version = "0.1.0"
edition = "2021"

[features]
default = []
transform = ["oxc"]


[dependencies]
rquickjs = { workspace = true, features = ["loader", "futures"] }
rquickjs-util = { path = "../rquickjs-util" }
oxc_resolver = { version = "2" }
oxc = { version = "0.36", features = [
  "transformer",
  "codegen",
  "sourcemap",
  "semantic",
], optional = true }
relative-path = { version = "1" }
parking_lot = { version = "0.12" }

tracing = { version = "0.1" }
geenie = { git = "https://github.com/fairy-render/geenie.git" }

[dev-dependencies]
futures = { version = "0.3" }
