[workspace]

resolver = "2"

members = [

  "klaver-image",
  "rquickjs-util",
  "klaver-fs",
  "klaver-dom",
  "klaver-wintercg",
  "rquickjs-modules",
  "klaver-cli",
  "klaver",
  "klaver-handlebars",
  "klaver-base",
  "klaver-timers",
  "klaver-runner",
  "klaver-worker",
  # "klaver-http",
]


[workspace.dependencies]
rquickjs = { version = "0.8", features = [
  "futures",
  "macro",
  "classes",
  "array-buffer",
] }
tokio = { version = "1" }
futures = { version = "0.3" }
event-listener = { version = "5" }
pin-project-lite = { version = "0.2" }


[profile.release]
lto = "fat"
panic = "abort"
codegen-units = 1
strip = "debuginfo"
