[workspace]

resolver = "2"

members = [
  "klaver",
  "klaver-cli",
  "klaver-compat", "klaver-crypto",
  "klaver-encoding",
  "klaver-http", "klaver-streams",
]


[workspace.dependencies]
rquickjs = { version = "0.6", features = [
  "futures",
  "macro",
  "classes",
  "array-buffer",
] }
tokio = { version = "1" }
futures = { version = "0.3" }


[profile.release]
lto = "fat"
panic = "abort"
