[workspace]

resolver = "2"

members = [

  # "klaver-gerning",
  "klaver-image",
  # "klaver-os",
  "rquickjs-util",
  "klaver-fs",
  "klaver-dom",
  "klaver-wintercg",
  "rquickjs-modules",
  "klaver-cli",
  "klaver",
  "klaver-handlebars", "klaver-http",
]


[workspace.dependencies]
rquickjs = { version = "0.8", features = [
  "futures",
  "macro",
  "classes",
  "array-buffer",
] }
tokio = { version = "1" }
futures = { version = "0.3" }


[profile.release]
lto = "fat"
panic = "abort"
codegen-units = 1
strip = "debuginfo"
