[build]
pre-build = [
  "apt-get update",
  'apt install clang libssl-dev -y',
] # can also be the path to a file to run

[target.x86_64-unknown-linux-gnu]
pre-build = [
  "dpkg --add-architecture $CROSS_DEB_ARCH",
  "apt-get update && apt-get install --assume-yes libssl-dev:$CROSS_DEB_ARCH",
]
