[package]
name = "rquickjs-util"
version = "0.1.0"
edition = "2021"

[features]
default = ["vaerdi"]
vaerdi = ["dep:vaerdi", "chrono"]
chrono = ["dep:chrono"]


[dependencies]
rquickjs = { workspace = true, features = [
  # "futures",
  "macro",
  "classes",
  "array-buffer",
] }
vaerdi = { git = "https://github.com/kildevaeld/vaerdi-rs", optional = true }
udled = { git = "https://github.com/kildevaeld/udled-rs" }
udled-helpers = { git = "https://github.com/kildevaeld/udled-rs" }

chrono = { version = "0.4", optional = true }

futures = { version = "0.3" }
