[package]
name = "klaver-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
color-eyre = "0.6"

tokio = { version = "1", features = ["rt", "macros", "fs"] }

klaver = { path = "../klaver", features = [
  "http",
  "encoding",
  "crypto",
  "transform",
] }
rquickjs.workspace = true

klaver-dom = { path = "../klaver-dom" }
klaver-fs = { path = "../klaver-fs" }
