[package]
name = "klaver-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "klaver"
path = "src/main.rs"

[dependencies]
klaver = { path = "../klaver", features = ["typescript"] }
klaver-compat = { path = "../klaver-compat" }
klaver-encoding = { path = "../klaver-encoding" }


tokio = { version = "1", features = ["rt", "macros"] }
