[package]
name = "klaver-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "klaver"
path = "src/main.rs"

[dependencies]
klaver-base = { path = "../klaver-base" }
klaver-os = { path = "../klaver-os" }
klaver-module = { path = "../klaver-module", features = ["typescript"] }
klaver-http = { path = "../klaver-http", features = ["reqwest"] }
klaver-compat = { path = "../klaver-compat" }


rquickjs = { version = "0.6", features = ["futures"] }
tokio = { version = "1", features = ["rt", "macros"] }
