[package]
name = "klaver-base"
version = "0.1.0"
edition = "2021"

[dependencies]
klaver-shared = { path = "../klaver-shared" }
rquickjs = { workspace = true }
encoding_rs = { version = "0.8" }
tokio = { version = "1", features = ["time", "sync", "macros"] }
slotmap = { version = "1.0", default-features = false }
extensions = { version = "0.2" }
futures = { version = "0.3" }
