[package]
name = "klaver-base"
version = "0.1.0"
edition = "2024"

[dependencies]
rquickjs.workspace = true
rquickjs-util = { path = "../rquickjs-util" }
async-channel = { version = "2" }

async-notify = { version = "0.3" }
