[package]
name = "klaver"
version = "0.1.0"
edition = "2021"

[features]
default = ["pool"]
pool = ["deadpool"]
typescript = [
  "swc",
  "swc_common",
  "swc_ecma_ast",
  "swc_ecma_parser",
  "swc_ecma_transforms_typescript",
  "swc_ecma_visit",
]


[dependencies]
rquickjs = { workspace = true, features = ["full-async", "parallel"] }
once_cell = "1"
tokio = { version = "1", features = ["macros", "time"] }
pin-project-lite = "0.2"
slotmap = { version = "1" }
extensions = { version = "0.2" }


deadpool = { version = "0.12", optional = true }


relative-path = { version = "1" }

# Typescript
swc = { version = "0.282.1", optional = true }
swc_common = { version = "0.36.0", optional = true }
swc_ecma_ast = { version = "0.117.0", optional = true }
swc_ecma_parser = { version = "0.148.0", features = [
  "verify",
  "typescript",
], optional = true }
swc_ecma_transforms_typescript = { version = "0.194.0", optional = true }
swc_ecma_transforms_react = { version = "0.189.0" }
swc_ecma_transforms_base = { version = "0.143.0" }
swc_ecma_visit = { version = "0.103.1", optional = true }


[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt", "time"] }

[[example]]
name = "klaver"
path = "examples/klaver.rs"


[[example]]
name = "pool"
path = "examples/pool.rs"
required-features = ["pool"]
