[package]
name = "klaver"
version = "0.1.0"
edition = "2021"

[features]
default = ["pool"]
pool = ["deadpool"]
typescript = [
  "swc",
  "swc_common",
  "swc_ecma_ast",
  "swc_ecma_visit",
  "swc_ecma_parser",
  "swc_ecma_transforms",
]


[dependencies]
klaver-shared = { path = "../klaver-shared" }
rquickjs = { workspace = true, features = ["full-async", "parallel"] }
once_cell = "1"
tokio = { version = "1", features = ["macros", "time"] }
pin-project-lite = "0.2"
slotmap = { version = "1" }
extensions = { version = "0.2" }
deadpool = { version = "0.12", optional = true }
relative-path = { version = "1" }
tracing = { version = "0.1" }

# Typescript
swc = { version = "0.282.2", optional = true }
swc_common = { version = "0.36.2", optional = true }
swc_ecma_ast = { version = "0.117.4", optional = true }
swc_ecma_parser = { version = "0.148.1", features = [
  "verify",
  "typescript",
], optional = true }
swc_ecma_visit = { version = "0.103.3", optional = true }
swc_ecma_transforms = { version = "0.235.0", optional = true }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt", "time"] }

[[example]]
name = "klaver"
path = "examples/klaver.rs"


[[example]]
name = "pool"
path = "examples/pool.rs"
required-features = ["pool"]
