[package]
name = "klaver"
version = "0.1.0"
edition = "2024"

[dependencies]
klaver-wintercg = { path = "../klaver-wintercg", features = ["module"] }
klaver-vm = { path = "../klaver-vm" }
klaver-modules = { path = "../klaver-modules" }
klaver-runner = { path = "../klaver-runner" }
klaver-base = { path = "../klaver-base" }
rquickjs = { workspace = true }
rquickjs-util = { path = "../rquickjs-util" }
futures.workspace = true
