[package]
name = "klaver"
version = "0.1.0"
edition = "2024"

[dependencies]
klaver-wintercg = { path = "../klaver-wintercg", features = [
    "module",
    "tokio",
] }
klaver-vm = { path = "../klaver-vm" }
klaver-modules = { path = "../klaver-modules" }
klaver-task = { path = "../klaver-task" }
klaver-base = { path = "../klaver-base" }
rquickjs = { workspace = true }
futures.workspace = true


[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
