[package]
name = "klaver"
version = "0.2.0"
edition = "2021"

[features]
default = []
transform = ["rquickjs-modules/transform"]
http = ["klaver-wintercg/http"]
encoding = ["klaver-wintercg/encoding"]
crypto = ["klaver-wintercg/crypto"]
icu = ["klaver-wintercg/icu"]
icu-compiled = ["klaver-wintercg/icu-compiled"]

pool = ["deadpool", "tokio/rt", "parallel"]
parallel = ["rquickjs/parallel"]


[[example]]
name = "pool"
path = "examples/pool.rs"
required-features = ["pool"]

[[example]]
name = "worker"
path = "examples/worker.rs"
required-features = ["pool"]

[dependencies]
futures.workspace = true
rquickjs.workspace = true
rquickjs-modules = { path = "../rquickjs-modules" }
rquickjs-util = { path = "../rquickjs-util" }
klaver-wintercg = { path = "../klaver-wintercg" }
tokio = { version = "1", features = ["sync"] }
deadpool = { version = "0.12", optional = true }


[dev-dependencies]
tokio = { version = "1", features = ["sync", "macros", "rt"] }
