[package]
name = "klaver"
version = "0.1.0"
edition = "2021"

[features]
pool = ["deadpool"]
typescript = [
  "swc",
  "swc_common",
  "swc_ecma_ast",
  "swc_ecma_parser",
  "swc_ecma_transforms_typescript",
  "swc_ecma_visit",
]


[dependencies]
rquickjs = { workspace = true, features = ["full-async", "parallel"] }
once_cell = "1"
tokio = { version = "1", features = ["macros", "time"] }
pin-project-lite = "0.2"
slotmap = { version = "1" }

deadpool = { version = "0.12", optional = true }


relative-path = { version = "1" }

# Typescript
swc = { version = "0.273.6", optional = true }
swc_common = { version = "0.33.17", optional = true }
swc_ecma_ast = { version = "0.112.2", optional = true }
swc_ecma_parser = { version = "0.143.3", features = [
  "verify",
  "typescript",
], optional = true }
swc_ecma_transforms_typescript = { version = "0.188.5", optional = true }
swc_ecma_visit = { version = "0.98.2", optional = true }


[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt", "time"] }

[[example]]
name = "klaver"
path = "examples/klaver.rs"


[[example]]
name = "pool"
path = "examples/pool.rs"
required-features = ["pool"]
