[package]
name = "klaver"
version = "0.2.0"
edition = "2024"

[features]
swc = ["klaver-modules/swc-transform"]

full = ["fetch", "crypto", "intl-backed"]

fetch = ["klaver-wintertc/fetch"]
crypto = ["klaver-wintertc/crypto"]
intl = ["klaver-wintertc/intl"]
intl-backed = ["klaver-wintertc/intl-backed"]

[dependencies]
klaver-wintertc = { path = "../klaver-wintertc", features = [
    "module",
    "tokio",
] }
klaver-vm = { path = "../klaver-vm" }
klaver-modules = { path = "../klaver-modules" }
klaver-runtime = { path = "../klaver-runtime" }
klaver-base = { path = "../klaver-base" }
rquickjs = { workspace = true }
futures.workspace = true


[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
