[package]
name = "klaver-os"
version = "0.1.0"
edition = "2024"

[dependencies]
rquickjs.workspace = true
klaver-util = { path = "../klaver-util" }
klaver-base = { path = "../klaver-base" }

sysinfo = { version = "0.37" }
