[package]
name = "klaver-module"
version = "0.1.0"
edition = "2021"

[features]
default = []
typescript = [
  "swc",
  "swc_common",
  "swc_ecma_ast",
  "swc_ecma_parser",
  "swc_ecma_transforms_typescript",
  "swc_ecma_visit",
]

[dependencies]
rquickjs = { version = "0.6", features = ["loader"] }
relative-path = { version = "1" }

swc = { version = "0.273.6", optional = true }
swc_common = { version = "0.33.17", optional = true }
swc_ecma_ast = { version = "0.112.2", optional = true }
swc_ecma_parser = { version = "0.143.3", features = [
  "verify",
  "typescript",
], optional = true }
swc_ecma_transforms_typescript = { version = "0.188.5", optional = true }
swc_ecma_visit = { version = "0.98.2", optional = true }
