[package]
name = "klaver-worker"
version = "0.1.0"
edition = "2021"

[features]
default = []
pool = ["deadpool", "tokio/sync"]
send = ["rquickjs/parallel"]

[dependencies]
tokio = { workspace = true, features = ["rt"] }
rquickjs = { workspace = true }
futures = { workspace = true }
slotmap = { version = "1" }
deadpool = { version = "0.12", optional = true }

[[example]]
bin = "examples/worker.rs"
name = "worker"
required-features = ["pool"]
