[package]
name = "klaver-os"
version = "0.1.0"
edition = "2021"

[dependencies]
klaver-shared = { path = "../klaver-shared" }
klaver-base = { path = "../klaver-base" }
rquickjs = { version = "0.6", features = [
  "classes",
  "properties",
  "futures",
  "array-buffer",
  "macro",
] }
tokio = { version = "1", features = ["fs", "process"] }
tokio-stream = { version = "0.1" }
tokio-util = { version = "0.7", features = ["io"] }

futures = { version = "0.3" }
